### ISSUE TITLE
How to create train_sequence.npy, and train_cluster_ids.npy.

### ISSUE THREAD

**Issue by Sadam1195** [HarryVolek/PyTorch_Speaker_Verification#56]
When I run the `dvector.py` file, it only creates test_sequence.npy, and test_cluster_ids.npy. How do I create train_sequence.npy, and train_cluster_ids.npy files with `dvector.py`?

**Comment by BarCodeReader** [comment]
you seriously????

`    if not train_saved and i > train_speaker_num:
        train_sequence = np.concatenate(train_sequence,axis=0)
        train_cluster_id = np.asarray(train_cluster_id)
        **np.save('train_sequence',train_sequence)
        np.save('train_cluster_id',train_cluster_id)**
        train_saved = True
        train_sequence = []
        train_cluster_id = []
        
train_sequence = np.concatenate(train_sequence,axis=0)
train_cluster_id = np.asarray(train_cluster_id)
**np.save('test_sequence',train_sequence)
np.save('test_cluster_id',train_cluster_id)**`

how come it will only give you test.npy???

**Comment by Sadam1195** [comment]
@BarCodeReader That's the thing which is bothering me. I don't know why it creates only `''test_sequence', 'test_cluster_id'` while it should create both train and test npy files when `train_saved = False` is set.

**Comment by BarCodeReader** [comment]
then means the i in the loop never triggers the condition...then probably you have some problem with your audio_path setting...

**Comment by Sadam1195** [comment]
Yes, I think too. I have let default settings `audio_path = glob.glob(os.path.dirname(hp.unprocessed_data)`) in `dvetor.py` file while I have changed this 

```
training: !!bool "true"
device: "cuda"
unprocessed_data: './voice samples/*/*/*.wav'
---
data:
    train_path: './train_tisv'
    train_path_unprocessed: './voice samples/train/*/*.wav'
    test_path: './test_tisv' 
    test_path_unprocessed: './voice samples/test/*/*.wav'
```

in the config file. Do you see anything odd?
